// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package com.app.novelvoice.netty.proto;

public final class ChatMessageProto {
  private ChatMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_app_novelvoice_netty_proto_ChatMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ChatMessage.proto\022\036com.app.novelvoice." +
      "netty.proto\"\312\001\n\013ChatMessage\022\021\n\tsender_id" +
      "\030\001 \001(\003\022\023\n\013receiver_id\030\002 \001(\003\022\017\n\007content\030\003" +
      " \001(\t\022\014\n\004type\030\004 \001(\005\022\021\n\ttimestamp\030\005 \001(\t\022\020\n" +
      "\010file_url\030\006 \001(\t\022\021\n\tfile_name\030\007 \001(\t\022\021\n\tfi" +
      "le_size\030\010 \001(\003\022\027\n\017sender_nickname\030\t \001(\t\022\025" +
      "\n\rsender_avatar\030\n \001(\tB2\n\036com.app.novelvo" +
      "ice.netty.protoB\020ChatMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_app_novelvoice_netty_proto_ChatMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor,
        new java.lang.String[] { "SenderId", "ReceiverId", "Content", "Type", "Timestamp", "FileUrl", "FileName", "FileSize", "SenderNickname", "SenderAvatar", });
  }

}
