// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package com.app.novelvoice.netty.proto;

public interface ChatMessageOrBuilder extends
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 sender_id = 1;</code>
   * @return The senderId.
   */
  long getSenderId();

  /**
   * <code>int64 receiver_id = 2;</code>
   * @return The receiverId.
   */
  long getReceiverId();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString getContentBytes();

  /**
   * <code>int32 type = 4;</code>
   * @return The type.
   */
  int getType();

  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString getTimestampBytes();

  /**
   * <code>string file_url = 6;</code>
   * @return The fileUrl.
   */
  java.lang.String getFileUrl();
  /**
   * <code>string file_url = 6;</code>
   * @return The bytes for fileUrl.
   */
  com.google.protobuf.ByteString getFileUrlBytes();

  /**
   * <code>string file_name = 7;</code>
   * @return The fileName.
   */
  java.lang.String getFileName();
  /**
   * <code>string file_name = 7;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString getFileNameBytes();

  /**
   * <code>int64 file_size = 8;</code>
   * @return The fileSize.
   */
  long getFileSize();

  /**
   * <code>string sender_nickname = 9;</code>
   * @return The senderNickname.
   */
  java.lang.String getSenderNickname();
  /**
   * <code>string sender_nickname = 9;</code>
   * @return The bytes for senderNickname.
   */
  com.google.protobuf.ByteString getSenderNicknameBytes();

  /**
   * <code>string sender_avatar = 10;</code>
   * @return The senderAvatar.
   */
  java.lang.String getSenderAvatar();
  /**
   * <code>string sender_avatar = 10;</code>
   * @return The bytes for senderAvatar.
   */
  com.google.protobuf.ByteString getSenderAvatarBytes();
}
