// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChatMessage.proto

package com.app.novelvoice.netty.proto;

/**
 * Protobuf type {@code com.app.novelvoice.netty.proto.ChatMessage}
 */
public final class ChatMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    ChatMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChatMessage.newBuilder() to construct.
  private ChatMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChatMessage() {
    content_ = "";
    timestamp_ = "";
    fileUrl_ = "";
    fileName_ = "";
    senderNickname_ = "";
    senderAvatar_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ChatMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChatMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            senderId_ = input.readInt64();
            break;
          }
          case 16: {
            receiverId_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            content_ = s;
            break;
          }
          case 32: {
            type_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();
            timestamp_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();
            fileUrl_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();
            fileName_ = s;
            break;
          }
          case 64: {
            fileSize_ = input.readInt64();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            senderNickname_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();
            senderAvatar_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ChatMessageProto.internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ChatMessageProto.internal_static_com_app_novelvoice_netty_proto_ChatMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ChatMessage.class, ChatMessage.Builder.class);
  }

  public static final int SENDER_ID_FIELD_NUMBER = 1;
  private long senderId_;
  /**
   * <code>int64 sender_id = 1;</code>
   * @return The senderId.
   */
  @java.lang.Override
  public long getSenderId() {
    return senderId_;
  }

  public static final int RECEIVER_ID_FIELD_NUMBER = 2;
  private long receiverId_;
  /**
   * <code>int64 receiver_id = 2;</code>
   * @return The receiverId.
   */
  @java.lang.Override
  public long getReceiverId() {
    return receiverId_;
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object content_;
  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>int32 type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public int getType() {
    return type_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 5;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>string timestamp = 5;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 5;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_URL_FIELD_NUMBER = 6;
  private volatile java.lang.Object fileUrl_;
  /**
   * <code>string file_url = 6;</code>
   * @return The fileUrl.
   */
  @java.lang.Override
  public java.lang.String getFileUrl() {
    java.lang.Object ref = fileUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string file_url = 6;</code>
   * @return The bytes for fileUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileUrlBytes() {
    java.lang.Object ref = fileUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_NAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object fileName_;
  /**
   * <code>string file_name = 7;</code>
   * @return The fileName.
   */
  @java.lang.Override
  public java.lang.String getFileName() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fileName_ = s;
      return s;
    }
  }
  /**
   * <code>string file_name = 7;</code>
   * @return The bytes for fileName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFileNameBytes() {
    java.lang.Object ref = fileName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fileName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILE_SIZE_FIELD_NUMBER = 8;
  private long fileSize_;
  /**
   * <code>int64 file_size = 8;</code>
   * @return The fileSize.
   */
  @java.lang.Override
  public long getFileSize() {
    return fileSize_;
  }

  public static final int SENDER_NICKNAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object senderNickname_;
  /**
   * <code>string sender_nickname = 9;</code>
   * @return The senderNickname.
   */
  @java.lang.Override
  public java.lang.String getSenderNickname() {
    java.lang.Object ref = senderNickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderNickname_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_nickname = 9;</code>
   * @return The bytes for senderNickname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderNicknameBytes() {
    java.lang.Object ref = senderNickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderNickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_AVATAR_FIELD_NUMBER = 10;
  private volatile java.lang.Object senderAvatar_;
  /**
   * <code>string sender_avatar = 10;</code>
   * @return The senderAvatar.
   */
  @java.lang.Override
  public java.lang.String getSenderAvatar() {
    java.lang.Object ref = senderAvatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      senderAvatar_ = s;
      return s;
    }
  }
  /**
   * <code>string sender_avatar = 10;</code>
   * @return The bytes for senderAvatar.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderAvatarBytes() {
    java.lang.Object ref = senderAvatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      senderAvatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (senderId_ != 0L) {
      output.writeInt64(1, senderId_);
    }
    if (receiverId_ != 0L) {
      output.writeInt64(2, receiverId_);
    }
    if (!getContentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
    }
    if (type_ != 0) {
      output.writeInt32(4, type_);
    }
    if (!getTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, timestamp_);
    }
    if (!getFileUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, fileUrl_);
    }
    if (!getFileNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, fileName_);
    }
    if (fileSize_ != 0L) {
      output.writeInt64(8, fileSize_);
    }
    if (!getSenderNicknameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, senderNickname_);
    }
    if (!getSenderAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, senderAvatar_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (senderId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, senderId_);
    }
    if (receiverId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, receiverId_);
    }
    if (!getContentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
    }
    if (type_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, type_);
    }
    if (!getTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, timestamp_);
    }
    if (!getFileUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, fileUrl_);
    }
    if (!getFileNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, fileName_);
    }
    if (fileSize_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(8, fileSize_);
    }
    if (!getSenderNicknameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, senderNickname_);
    }
    if (!getSenderAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, senderAvatar_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ChatMessage)) {
      return super.equals(obj);
    }
    ChatMessage other = (ChatMessage) obj;

    if (getSenderId()
        != other.getSenderId()) return false;
    if (getReceiverId()
        != other.getReceiverId()) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (getType()
        != other.getType()) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (!getFileUrl()
        .equals(other.getFileUrl())) return false;
    if (!getFileName()
        .equals(other.getFileName())) return false;
    if (getFileSize()
        != other.getFileSize()) return false;
    if (!getSenderNickname()
        .equals(other.getSenderNickname())) return false;
    if (!getSenderAvatar()
        .equals(other.getSenderAvatar())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SENDER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSenderId());
    hash = (37 * hash) + RECEIVER_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getReceiverId());
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + FILE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getFileUrl().hashCode();
    hash = (37 * hash) + FILE_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFileName().hashCode();
    hash = (37 * hash) + FILE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFileSize());
    hash = (37 * hash) + SENDER_NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSenderNickname().hashCode();
    hash = (37 * hash) + SENDER_AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getSenderAvatar().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ChatMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ChatMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ChatMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ChatMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ChatMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ChatMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.app.novelvoice.netty.proto.ChatMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      ChatMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChatMessageProto.internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChatMessageProto.internal_static_com_app_novelvoice_netty_proto_ChatMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChatMessage.class, ChatMessage.Builder.class);
    }

    // Construct using ChatMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      senderId_ = 0L;
      receiverId_ = 0L;
      content_ = "";
      type_ = 0;
      timestamp_ = "";
      fileUrl_ = "";
      fileName_ = "";
      fileSize_ = 0L;
      senderNickname_ = "";
      senderAvatar_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ChatMessageProto.internal_static_com_app_novelvoice_netty_proto_ChatMessage_descriptor;
    }

    @java.lang.Override
    public ChatMessage getDefaultInstanceForType() {
      return ChatMessage.getDefaultInstance();
    }

    @java.lang.Override
    public ChatMessage build() {
      ChatMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ChatMessage buildPartial() {
      ChatMessage result = new ChatMessage(this);
      result.senderId_ = senderId_;
      result.receiverId_ = receiverId_;
      result.content_ = content_;
      result.type_ = type_;
      result.timestamp_ = timestamp_;
      result.fileUrl_ = fileUrl_;
      result.fileName_ = fileName_;
      result.fileSize_ = fileSize_;
      result.senderNickname_ = senderNickname_;
      result.senderAvatar_ = senderAvatar_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ChatMessage) {
        return mergeFrom((ChatMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ChatMessage other) {
      if (other == ChatMessage.getDefaultInstance()) return this;
      if (other.getSenderId() != 0L) {
        setSenderId(other.getSenderId());
      }
      if (other.getReceiverId() != 0L) {
        setReceiverId(other.getReceiverId());
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        onChanged();
      }
      if (other.getType() != 0) {
        setType(other.getType());
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (!other.getFileUrl().isEmpty()) {
        fileUrl_ = other.fileUrl_;
        onChanged();
      }
      if (!other.getFileName().isEmpty()) {
        fileName_ = other.fileName_;
        onChanged();
      }
      if (other.getFileSize() != 0L) {
        setFileSize(other.getFileSize());
      }
      if (!other.getSenderNickname().isEmpty()) {
        senderNickname_ = other.senderNickname_;
        onChanged();
      }
      if (!other.getSenderAvatar().isEmpty()) {
        senderAvatar_ = other.senderAvatar_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ChatMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ChatMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long senderId_ ;
    /**
     * <code>int64 sender_id = 1;</code>
     * @return The senderId.
     */
    @java.lang.Override
    public long getSenderId() {
      return senderId_;
    }
    /**
     * <code>int64 sender_id = 1;</code>
     * @param value The senderId to set.
     * @return This builder for chaining.
     */
    public Builder setSenderId(long value) {
      senderId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 sender_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderId() {
      senderId_ = 0L;
      onChanged();
      return this;
    }

    private long receiverId_ ;
    /**
     * <code>int64 receiver_id = 2;</code>
     * @return The receiverId.
     */
    @java.lang.Override
    public long getReceiverId() {
      return receiverId_;
    }
    /**
     * <code>int64 receiver_id = 2;</code>
     * @param value The receiverId to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverId(long value) {
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 receiver_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiverId() {
      receiverId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      content_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      content_ = value;
      onChanged();
      return this;
    }

    private int type_ ;
    /**
     * <code>int32 type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }
    /**
     * <code>int32 type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 5;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 5;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 5;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 5;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      timestamp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileUrl_ = "";
    /**
     * <code>string file_url = 6;</code>
     * @return The fileUrl.
     */
    public java.lang.String getFileUrl() {
      java.lang.Object ref = fileUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_url = 6;</code>
     * @return The bytes for fileUrl.
     */
    public com.google.protobuf.ByteString
        getFileUrlBytes() {
      java.lang.Object ref = fileUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_url = 6;</code>
     * @param value The fileUrl to set.
     * @return This builder for chaining.
     */
    public Builder setFileUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      fileUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_url = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileUrl() {
      fileUrl_ = getDefaultInstance().getFileUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string file_url = 6;</code>
     * @param value The bytes for fileUrl to set.
     * @return This builder for chaining.
     */
    public Builder setFileUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      fileUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fileName_ = "";
    /**
     * <code>string file_name = 7;</code>
     * @return The fileName.
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string file_name = 7;</code>
     * @return The bytes for fileName.
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string file_name = 7;</code>
     * @param value The fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      fileName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileName() {
      fileName_ = getDefaultInstance().getFileName();
      onChanged();
      return this;
    }
    /**
     * <code>string file_name = 7;</code>
     * @param value The bytes for fileName to set.
     * @return This builder for chaining.
     */
    public Builder setFileNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      fileName_ = value;
      onChanged();
      return this;
    }

    private long fileSize_ ;
    /**
     * <code>int64 file_size = 8;</code>
     * @return The fileSize.
     */
    @java.lang.Override
    public long getFileSize() {
      return fileSize_;
    }
    /**
     * <code>int64 file_size = 8;</code>
     * @param value The fileSize to set.
     * @return This builder for chaining.
     */
    public Builder setFileSize(long value) {
      fileSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 file_size = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileSize() {
      fileSize_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object senderNickname_ = "";
    /**
     * <code>string sender_nickname = 9;</code>
     * @return The senderNickname.
     */
    public java.lang.String getSenderNickname() {
      java.lang.Object ref = senderNickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderNickname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_nickname = 9;</code>
     * @return The bytes for senderNickname.
     */
    public com.google.protobuf.ByteString
        getSenderNicknameBytes() {
      java.lang.Object ref = senderNickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_nickname = 9;</code>
     * @param value The senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      senderNickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_nickname = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderNickname() {
      senderNickname_ = getDefaultInstance().getSenderNickname();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_nickname = 9;</code>
     * @param value The bytes for senderNickname to set.
     * @return This builder for chaining.
     */
    public Builder setSenderNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      senderNickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object senderAvatar_ = "";
    /**
     * <code>string sender_avatar = 10;</code>
     * @return The senderAvatar.
     */
    public java.lang.String getSenderAvatar() {
      java.lang.Object ref = senderAvatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senderAvatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string sender_avatar = 10;</code>
     * @return The bytes for senderAvatar.
     */
    public com.google.protobuf.ByteString
        getSenderAvatarBytes() {
      java.lang.Object ref = senderAvatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderAvatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sender_avatar = 10;</code>
     * @param value The senderAvatar to set.
     * @return This builder for chaining.
     */
    public Builder setSenderAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
      senderAvatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sender_avatar = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearSenderAvatar() {
      senderAvatar_ = getDefaultInstance().getSenderAvatar();
      onChanged();
      return this;
    }
    /**
     * <code>string sender_avatar = 10;</code>
     * @param value The bytes for senderAvatar to set.
     * @return This builder for chaining.
     */
    public Builder setSenderAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      senderAvatar_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

  }

  private static final ChatMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ChatMessage();
  }

  public static ChatMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChatMessage>
      PARSER = new com.google.protobuf.AbstractParser<ChatMessage>() {
    @java.lang.Override
    public ChatMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChatMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChatMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChatMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ChatMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
